cors:
  allowed-origins: >
    http://localhost:3000,
    http://localhost:8081,
    http://localhost:8084,
    http://t1101.p.ssafy.io,
    http://t1101.p.ssafy.io:3000,
    https://t1101.p.ssafy.io,
    https://t1101.p.ssafy.io:3000
